# Generated by Django 5.0 on 2024-01-14 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CarApp', '0003_carmodel_quantity_alter_carmodel_image_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='CarApp.carmodel')),
            ],
        ),
    ]
