# Generated by Django 5.0 on 2024-01-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
